# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_auto_20171005_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
