# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='camp',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='camp',
            name='state',
            field=models.CharField(max_length=256),
        ),
    ]
