# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 17:56
from __future__ import unicode_literals

import camp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_auto_20171005_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=camp.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='camp',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
