# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 12:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_auto_20171008_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
